<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Setup 2fa</title>
</head>
<body>
    <div class="faq container mt-5" style="display: flex;align-items: center;height: 100vh;">
        <div class="faq-layouting layout-spacing" style="width: 100%;">
            <div class="fq-comman-question-wrapper">
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="text-center pb-3 mb-3" style="border-bottom: 1px solid #191e3a;">Enter your 2FA password</h3>
                        <p class="text-center mb-5" style="font-size: 14px;">Scan the QR code below and enter the verification code generated by <strong class="text-danger">Google Authenticator</strong> app on your phone.</p>
                        
                        <div class="row mb-5">
                            <div class="col-12 text-center mb-lg-0 mb-4">
                                <img src="{{$qrCodeUrl}}">
                            </div>     
                        </div>
                        <div class="d-flex" style="justify-content: center;">
                            <div class="input-group mb-4" style="width: 30em">
                                <input id="vc" type="text" class="form-control" placeholder="Verification Code" aria-label="Verification Code">
                                <div class="input-group-append">
                                    <button id="checkVc" class="btn btn-primary" type="button">Verify</button>
                                </div>
                            </div>   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.19/dist/sweetalert2.all.min.js"></script>
<script>
    $('#checkVc').on('click', function(){
        $.post('/user/check/vc',{
            _token  :   $('meta[name="csrf-token"]').attr('content'),
            vc      :   $('#vc').val()
        },
        function(response){
            if(response.status == 'true'){
                swal({
                    title: 'Good job!',
                    text: "Code verified!",
                    type: 'success',
                    padding: '2em'
                });

                $(document).on('click', function(){
                    location.reload();
                });
            }
            else{
                swal({
                    title: 'Error!',
                    text: "Incorrect Verification Code!",
                    type: 'warning',
                    padding: '2em'
                });
            }
        });
    });
</script>
</html>